info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Get a message indicating that the Gin-Gonic server is up and running
      produces:
      - application/json
      responses:
        "200":
          description: status message
          schema:
            additionalProperties: true
            type: object
      summary: Show server running status
      tags:
      - server
  /api/v1/user:
    get:
      consumes:
      - application/json
      description: Get list of dummy users from the endpoint
      produces:
      - application/json
      responses:
        "200":
          description: status message
          schema:
            additionalProperties: true
            type: object
      summary: Get list of dummy users
      tags:
      - users
swagger: "2.0"
